# Form implementation generated from reading ui file 'EspiropapaUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MultithreadInterface(object):
    def setupUi(self, MultithreadInterface):
        MultithreadInterface.setObjectName("MultithreadInterface")
        MultithreadInterface.resize(1241, 588)
        self.frame1 = QtWidgets.QLabel(parent=MultithreadInterface)
        self.frame1.setGeometry(QtCore.QRect(30, 80, 571, 381))
        self.frame1.setStyleSheet("background-color: rgba(46, 47, 58,30);")
        self.frame1.setText("")
        self.frame1.setObjectName("frame1")
        self.frame2 = QtWidgets.QLabel(parent=MultithreadInterface)
        self.frame2.setGeometry(QtCore.QRect(610, 70, 601, 391))
        self.frame2.setStyleSheet("background-color: rgba(46, 47, 58,30);")
        self.frame2.setText("")
        self.frame2.setObjectName("frame2")
        self.stopButton = QtWidgets.QPushButton(parent=MultithreadInterface)
        self.stopButton.setGeometry(QtCore.QRect(390, 510, 151, 51))
        self.stopButton.setObjectName("stopButton")
        self.startButton = QtWidgets.QPushButton(parent=MultithreadInterface)
        self.startButton.setGeometry(QtCore.QRect(160, 510, 151, 51))
        self.startButton.setObjectName("startButton")

        self.retranslateUi(MultithreadInterface)
        self.stopButton.clicked.connect(MultithreadInterface.stopVideo) # type: ignore
        self.startButton.clicked.connect(MultithreadInterface.startVideo) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MultithreadInterface)

    def retranslateUi(self, MultithreadInterface):
        _translate = QtCore.QCoreApplication.translate
        MultithreadInterface.setWindowTitle(_translate("MultithreadInterface", "Form"))
        self.stopButton.setText(_translate("MultithreadInterface", "Stop"))
        self.startButton.setText(_translate("MultithreadInterface", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MultithreadInterface = QtWidgets.QWidget()
    ui = Ui_MultithreadInterface()
    ui.setupUi(MultithreadInterface)
    MultithreadInterface.show()
    sys.exit(app.exec())
