# Form implementation generated from reading ui file 'utils/Interface/uiDesigns/addParcelaWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addParcelaWindow(object):
    def setupUi(self, addParcelaWindow):
        addParcelaWindow.setObjectName("addParcelaWindow")
        addParcelaWindow.resize(979, 1080)
        addParcelaWindow.setStyleSheet("border-radius: 15px;\n"
"background-color: rgba(61, 255, 181,0);")
        self.gridLayout = QtWidgets.QGridLayout(addParcelaWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.logoutGroupBox = QtWidgets.QGroupBox(parent=addParcelaWindow)
        self.logoutGroupBox.setStyleSheet("background-color: rgb(76, 165, 34);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"\n"
"")
        self.logoutGroupBox.setTitle("")
        self.logoutGroupBox.setObjectName("logoutGroupBox")
        self.logoutGroupBoxLayout = QtWidgets.QGridLayout(self.logoutGroupBox)
        self.logoutGroupBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.logoutGroupBoxLayout.setSpacing(0)
        self.logoutGroupBoxLayout.setObjectName("logoutGroupBoxLayout")
        spacerItem = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoutGroupBoxLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.titleLabel = QtWidgets.QLabel(parent=self.logoutGroupBox)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(30)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.logoutGroupBoxLayout.addWidget(self.titleLabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoutGroupBoxLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.logoutGroupBoxLayout.setColumnStretch(0, 30)
        self.logoutGroupBoxLayout.setColumnStretch(1, 40)
        self.logoutGroupBoxLayout.setColumnStretch(2, 20)
        self.gridLayout.addWidget(self.logoutGroupBox, 0, 0, 1, 1)
        self.closeDialogButton = QtWidgets.QPushButton(parent=addParcelaWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeDialogButton.sizePolicy().hasHeightForWidth())
        self.closeDialogButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(24)
        font.setBold(False)
        self.closeDialogButton.setFont(font)
        self.closeDialogButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 165, 34);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 25px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(190, 67, 42);\n"
"}")
        self.closeDialogButton.setObjectName("closeDialogButton")
        self.gridLayout.addWidget(self.closeDialogButton, 0, 1, 1, 1)
        self.logoutOptionsGroupBox = QtWidgets.QGroupBox(parent=addParcelaWindow)
        self.logoutOptionsGroupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(216, 216, 216);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;")
        self.logoutOptionsGroupBox.setTitle("")
        self.logoutOptionsGroupBox.setObjectName("logoutOptionsGroupBox")
        self.acceptDialogButton = QtWidgets.QPushButton(parent=self.logoutOptionsGroupBox)
        self.acceptDialogButton.setGeometry(QtCore.QRect(570, 880, 331, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptDialogButton.sizePolicy().hasHeightForWidth())
        self.acceptDialogButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(True)
        self.acceptDialogButton.setFont(font)
        self.acceptDialogButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(116, 116, 116);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(76, 165, 34);\n"
"}")
        self.acceptDialogButton.setObjectName("acceptDialogButton")
        self.cancelDialogButton = QtWidgets.QPushButton(parent=self.logoutOptionsGroupBox)
        self.cancelDialogButton.setGeometry(QtCore.QRect(110, 870, 331, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelDialogButton.sizePolicy().hasHeightForWidth())
        self.cancelDialogButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(True)
        self.cancelDialogButton.setFont(font)
        self.cancelDialogButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(116, 116, 116);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(190, 67, 42);\n"
"}")
        self.cancelDialogButton.setObjectName("cancelDialogButton")
        self.groupBox = QtWidgets.QGroupBox(parent=self.logoutOptionsGroupBox)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 931, 831))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 40px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.addSeparacionLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addSeparacionLineEdit.setGeometry(QtCore.QRect(720, 290, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addSeparacionLineEdit.setFont(font)
        self.addSeparacionLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addSeparacionLineEdit.setText("")
        self.addSeparacionLineEdit.setMaxLength(6)
        self.addSeparacionLineEdit.setObjectName("addSeparacionLineEdit")
        self.fechaLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.fechaLabel.setGeometry(QtCore.QRect(30, 180, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.fechaLabel.setFont(font)
        self.fechaLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fechaLabel.setObjectName("fechaLabel")
        self.parcelaNameLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.parcelaNameLabel.setGeometry(QtCore.QRect(30, 100, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.parcelaNameLabel.setFont(font)
        self.parcelaNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.parcelaNameLabel.setObjectName("parcelaNameLabel")
        self.tamanoLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.tamanoLabel.setGeometry(QtCore.QRect(120, 280, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.tamanoLabel.setFont(font)
        self.tamanoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tamanoLabel.setObjectName("tamanoLabel")
        self.cantidadLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.cantidadLabel.setGeometry(QtCore.QRect(20, 400, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.cantidadLabel.setFont(font)
        self.cantidadLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cantidadLabel.setObjectName("cantidadLabel")
        self.addParcelaLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addParcelaLineEdit.setGeometry(QtCore.QRect(290, 100, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addParcelaLineEdit.setFont(font)
        self.addParcelaLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addParcelaLineEdit.setText("")
        self.addParcelaLineEdit.setMaxLength(40)
        self.addParcelaLineEdit.setObjectName("addParcelaLineEdit")
        self.addTamanoLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addTamanoLineEdit.setGeometry(QtCore.QRect(290, 280, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addTamanoLineEdit.setFont(font)
        self.addTamanoLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addTamanoLineEdit.setText("")
        self.addTamanoLineEdit.setMaxLength(10)
        self.addTamanoLineEdit.setObjectName("addTamanoLineEdit")
        self.addCantidadLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addCantidadLineEdit.setGeometry(QtCore.QRect(290, 400, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addCantidadLineEdit.setFont(font)
        self.addCantidadLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addCantidadLineEdit.setText("")
        self.addCantidadLineEdit.setMaxLength(9)
        self.addCantidadLineEdit.setObjectName("addCantidadLineEdit")
        self.separacionLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.separacionLabel.setGeometry(QtCore.QRect(550, 290, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.separacionLabel.setFont(font)
        self.separacionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.separacionLabel.setObjectName("separacionLabel")
        self.subtitleLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.subtitleLabel.setGeometry(QtCore.QRect(200, 20, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(True)
        self.subtitleLabel.setFont(font)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.errorLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.errorLabel.setGeometry(QtCore.QRect(20, 780, 881, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: rgb(255, 19, 19);")
        self.errorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.distanciaLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.distanciaLabel.setGeometry(QtCore.QRect(550, 390, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.distanciaLabel.setFont(font)
        self.distanciaLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.distanciaLabel.setObjectName("distanciaLabel")
        self.addEstadoLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addEstadoLineEdit.setGeometry(QtCore.QRect(290, 490, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addEstadoLineEdit.setFont(font)
        self.addEstadoLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addEstadoLineEdit.setText("")
        self.addEstadoLineEdit.setMaxLength(40)
        self.addEstadoLineEdit.setObjectName("addEstadoLineEdit")
        self.estadoLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.estadoLabel.setGeometry(QtCore.QRect(90, 490, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.estadoLabel.setFont(font)
        self.estadoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.estadoLabel.setObjectName("estadoLabel")
        self.addDistanciaLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addDistanciaLineEdit.setGeometry(QtCore.QRect(720, 390, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addDistanciaLineEdit.setFont(font)
        self.addDistanciaLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addDistanciaLineEdit.setText("")
        self.addDistanciaLineEdit.setMaxLength(6)
        self.addDistanciaLineEdit.setObjectName("addDistanciaLineEdit")
        self.addFechaDateEdit = QtWidgets.QDateEdit(parent=self.groupBox)
        self.addFechaDateEdit.setGeometry(QtCore.QRect(290, 190, 201, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 165, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 165, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 165, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 165, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 165, 34))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Link, brush)
        self.addFechaDateEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.addFechaDateEdit.setFont(font)
        self.addFechaDateEdit.setStyleSheet("QDateEdit{\n"
"    font: 18pt \"Arial Rounded MT Bold\";\n"
"padding-left: 15px;\n"
"border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"}\n"
"QAbstractSpinBox::up-button {\n"
"image: url(Recursos/Icons/upArrowB.svg);\n"
"border-top-right-radius: 10px;\n"
"}\n"
"QAbstractSpinBox::up-button:hover {\n"
"background-color: rgb(136, 136, 136);\n"
"border-bottom-left-radius: 10px;\n"
"}\n"
"QAbstractSpinBox::up-button:pressed {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color: rgb(156, 156, 156);\n"
"}\n"
"QAbstractSpinBox::down-button {\n"
"image: url(Recursos/Icons/downArrowB.svg);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"}\n"
"QAbstractSpinBox::down-button:hover {\n"
"background-color: rgb(136, 136, 136);\n"
"}\n"
"QAbstractSpinBox::down-button:pressed {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color: rgb(156, 156, 156);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.addFechaDateEdit.setWrapping(False)
        self.addFechaDateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.addFechaDateEdit.setAccelerated(True)
        self.addFechaDateEdit.setCalendarPopup(False)
        self.addFechaDateEdit.setDate(QtCore.QDate(2001, 1, 1))
        self.addFechaDateEdit.setObjectName("addFechaDateEdit")
        self.coordsGroupBox = QtWidgets.QGroupBox(parent=self.groupBox)
        self.coordsGroupBox.setGeometry(QtCore.QRect(40, 590, 851, 191))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.coordsGroupBox.setFont(font)
        self.coordsGroupBox.setStyleSheet("QGroupBox{\n"
"border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"    color: rgb(116, 116, 116);\n"
"}\n"
"QGroupBox::title {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"border-bottom: 3px solid;\n"
"border-right: 3px solid;\n"
"border-bottom-right-radius: 10px;\n"
"border-color:rgb(156, 156, 156);\n"
"}\n"
"")
        self.coordsGroupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.coordsGroupBox.setFlat(False)
        self.coordsGroupBox.setCheckable(False)
        self.coordsGroupBox.setObjectName("coordsGroupBox")
        self.latitudLabel = QtWidgets.QLabel(parent=self.coordsGroupBox)
        self.latitudLabel.setGeometry(QtCore.QRect(30, 40, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.latitudLabel.setFont(font)
        self.latitudLabel.setStyleSheet("border: none;")
        self.latitudLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.latitudLabel.setObjectName("latitudLabel")
        self.addLatitudLineEdit = QtWidgets.QLineEdit(parent=self.coordsGroupBox)
        self.addLatitudLineEdit.setGeometry(QtCore.QRect(130, 40, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addLatitudLineEdit.setFont(font)
        self.addLatitudLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addLatitudLineEdit.setText("")
        self.addLatitudLineEdit.setMaxLength(10)
        self.addLatitudLineEdit.setObjectName("addLatitudLineEdit")
        self.longitudLabel = QtWidgets.QLabel(parent=self.coordsGroupBox)
        self.longitudLabel.setGeometry(QtCore.QRect(440, 40, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.longitudLabel.setFont(font)
        self.longitudLabel.setStyleSheet("border: none;\n"
"")
        self.longitudLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.longitudLabel.setObjectName("longitudLabel")
        self.addLongitudLineEdit = QtWidgets.QLineEdit(parent=self.coordsGroupBox)
        self.addLongitudLineEdit.setGeometry(QtCore.QRect(600, 40, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addLongitudLineEdit.setFont(font)
        self.addLongitudLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addLongitudLineEdit.setText("")
        self.addLongitudLineEdit.setMaxLength(10)
        self.addLongitudLineEdit.setObjectName("addLongitudLineEdit")
        self.setCoordsButton = QtWidgets.QPushButton(parent=self.coordsGroupBox)
        self.setCoordsButton.setGeometry(QtCore.QRect(190, 130, 461, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setCoordsButton.sizePolicy().hasHeightForWidth())
        self.setCoordsButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(True)
        self.setCoordsButton.setFont(font)
        self.setCoordsButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(156, 156, 156);\n"
"border-radius: 0px;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 87, 105);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.setCoordsButton.setObjectName("setCoordsButton")
        self.gridLayout.addWidget(self.logoutOptionsGroupBox, 1, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 90)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setRowStretch(0, 10)
        self.gridLayout.setRowStretch(1, 90)

        self.retranslateUi(addParcelaWindow)
        self.closeDialogButton.clicked.connect(addParcelaWindow.closeDialog) # type: ignore
        self.cancelDialogButton.clicked.connect(addParcelaWindow.closeDialog) # type: ignore
        self.acceptDialogButton.clicked.connect(addParcelaWindow.doDialogAction) # type: ignore
        self.setCoordsButton.clicked.connect(addParcelaWindow.setCoordinates) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addParcelaWindow)
        addParcelaWindow.setTabOrder(self.closeDialogButton, self.addParcelaLineEdit)
        addParcelaWindow.setTabOrder(self.addParcelaLineEdit, self.addTamanoLineEdit)
        addParcelaWindow.setTabOrder(self.addTamanoLineEdit, self.addCantidadLineEdit)
        addParcelaWindow.setTabOrder(self.addCantidadLineEdit, self.addSeparacionLineEdit)
        addParcelaWindow.setTabOrder(self.addSeparacionLineEdit, self.cancelDialogButton)
        addParcelaWindow.setTabOrder(self.cancelDialogButton, self.acceptDialogButton)

    def retranslateUi(self, addParcelaWindow):
        _translate = QtCore.QCoreApplication.translate
        addParcelaWindow.setWindowTitle(_translate("addParcelaWindow", "Form"))
        self.titleLabel.setText(_translate("addParcelaWindow", "Agregar Nueva Parcela"))
        self.closeDialogButton.setText(_translate("addParcelaWindow", "X"))
        self.acceptDialogButton.setText(_translate("addParcelaWindow", "Agregar"))
        self.cancelDialogButton.setText(_translate("addParcelaWindow", "Cancelar"))
        self.addSeparacionLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. 25.00"))
        self.fechaLabel.setText(_translate("addParcelaWindow", "Fecha de Plantación:"))
        self.parcelaNameLabel.setText(_translate("addParcelaWindow", "Nombre de la Parcela:"))
        self.tamanoLabel.setText(_translate("addParcelaWindow", "<html><head/><body><p>Tamaño de </p><p>la Hectárea:</p></body></html>"))
        self.cantidadLabel.setText(_translate("addParcelaWindow", "Cantidad Plantada:"))
        self.addParcelaLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. Paparcela"))
        self.addTamanoLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. 20.00"))
        self.addCantidadLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. 35000"))
        self.separacionLabel.setText(_translate("addParcelaWindow", "<html><head/><body><p align=\"center\">Separación </p><p align=\"center\">entre Cultivo:</p></body></html>"))
        self.subtitleLabel.setText(_translate("addParcelaWindow", "Ingrese los datos de la Parcela"))
        self.errorLabel.setText(_translate("addParcelaWindow", "Invalid Data"))
        self.distanciaLabel.setText(_translate("addParcelaWindow", "<html><head/><body><p align=\"center\">Distancia </p><p align=\"center\">entre Surcos:</p></body></html>"))
        self.addEstadoLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. En producción "))
        self.estadoLabel.setText(_translate("addParcelaWindow", "Estado Parcela:"))
        self.addDistanciaLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. 90.00"))
        self.coordsGroupBox.setTitle(_translate("addParcelaWindow", "Coordenadas"))
        self.latitudLabel.setText(_translate("addParcelaWindow", "Latitud"))
        self.addLatitudLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. 2447.08700"))
        self.longitudLabel.setText(_translate("addParcelaWindow", "Longitud:"))
        self.addLongitudLineEdit.setPlaceholderText(_translate("addParcelaWindow", "Ej. 12100.52210"))
        self.setCoordsButton.setText(_translate("addParcelaWindow", "Utilizar coordenadas actuales"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addParcelaWindow = QtWidgets.QWidget()
    ui = Ui_addParcelaWindow()
    ui.setupUi(addParcelaWindow)
    addParcelaWindow.show()
    sys.exit(app.exec())
