# Form implementation generated from reading ui file 'utils/Interface/uiDesigns/addVariedadWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addVariedadWindow(object):
    def setupUi(self, addVariedadWindow):
        addVariedadWindow.setObjectName("addVariedadWindow")
        addVariedadWindow.resize(979, 819)
        addVariedadWindow.setStyleSheet("border-radius: 15px;\n"
"background-color: rgba(61, 255, 181,0);")
        self.gridLayout = QtWidgets.QGridLayout(addVariedadWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.topBarGroupBox = QtWidgets.QGroupBox(parent=addVariedadWindow)
        self.topBarGroupBox.setStyleSheet("background-color: rgb(76, 165, 34);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"\n"
"")
        self.topBarGroupBox.setTitle("")
        self.topBarGroupBox.setObjectName("topBarGroupBox")
        self.logoutGroupBoxLayout = QtWidgets.QGridLayout(self.topBarGroupBox)
        self.logoutGroupBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.logoutGroupBoxLayout.setSpacing(0)
        self.logoutGroupBoxLayout.setObjectName("logoutGroupBoxLayout")
        spacerItem = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoutGroupBoxLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.titleLabel = QtWidgets.QLabel(parent=self.topBarGroupBox)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(30)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.logoutGroupBoxLayout.addWidget(self.titleLabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoutGroupBoxLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.logoutGroupBoxLayout.setColumnStretch(0, 30)
        self.logoutGroupBoxLayout.setColumnStretch(1, 40)
        self.logoutGroupBoxLayout.setColumnStretch(2, 15)
        self.gridLayout.addWidget(self.topBarGroupBox, 0, 0, 1, 1)
        self.closeDialogButton = QtWidgets.QPushButton(parent=addVariedadWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeDialogButton.sizePolicy().hasHeightForWidth())
        self.closeDialogButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(24)
        font.setBold(False)
        self.closeDialogButton.setFont(font)
        self.closeDialogButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 165, 34);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 25px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(190, 67, 42);\n"
"}")
        self.closeDialogButton.setObjectName("closeDialogButton")
        self.gridLayout.addWidget(self.closeDialogButton, 0, 1, 1, 1)
        self.logoutOptionsGroupBox = QtWidgets.QGroupBox(parent=addVariedadWindow)
        self.logoutOptionsGroupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(216, 216, 216);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;")
        self.logoutOptionsGroupBox.setTitle("")
        self.logoutOptionsGroupBox.setObjectName("logoutOptionsGroupBox")
        self.acceptDialogButton = QtWidgets.QPushButton(parent=self.logoutOptionsGroupBox)
        self.acceptDialogButton.setGeometry(QtCore.QRect(560, 620, 331, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptDialogButton.sizePolicy().hasHeightForWidth())
        self.acceptDialogButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(True)
        self.acceptDialogButton.setFont(font)
        self.acceptDialogButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(116, 116, 116);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(76, 165, 34);\n"
"}")
        self.acceptDialogButton.setObjectName("acceptDialogButton")
        self.cancelDialogButton = QtWidgets.QPushButton(parent=self.logoutOptionsGroupBox)
        self.cancelDialogButton.setGeometry(QtCore.QRect(80, 620, 331, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelDialogButton.sizePolicy().hasHeightForWidth())
        self.cancelDialogButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(True)
        self.cancelDialogButton.setFont(font)
        self.cancelDialogButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(116, 116, 116);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(190, 67, 42);\n"
"}")
        self.cancelDialogButton.setObjectName("cancelDialogButton")
        self.groupBox = QtWidgets.QGroupBox(parent=self.logoutOptionsGroupBox)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 931, 571))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 40px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.tamanoLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.tamanoLabel.setGeometry(QtCore.QRect(50, 300, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.tamanoLabel.setFont(font)
        self.tamanoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tamanoLabel.setObjectName("tamanoLabel")
        self.variedadNameLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.variedadNameLabel.setGeometry(QtCore.QRect(50, 100, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.variedadNameLabel.setFont(font)
        self.variedadNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.variedadNameLabel.setObjectName("variedadNameLabel")
        self.tiempoLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.tiempoLabel.setGeometry(QtCore.QRect(50, 200, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.tiempoLabel.setFont(font)
        self.tiempoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tiempoLabel.setObjectName("tiempoLabel")
        self.costoLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.costoLabel.setGeometry(QtCore.QRect(50, 400, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setKerning(True)
        self.costoLabel.setFont(font)
        self.costoLabel.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.costoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.costoLabel.setObjectName("costoLabel")
        self.addVariedadLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addVariedadLineEdit.setGeometry(QtCore.QRect(380, 100, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addVariedadLineEdit.setFont(font)
        self.addVariedadLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addVariedadLineEdit.setText("")
        self.addVariedadLineEdit.setMaxLength(30)
        self.addVariedadLineEdit.setObjectName("addVariedadLineEdit")
        self.addMaduracionLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addMaduracionLineEdit.setGeometry(QtCore.QRect(380, 200, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addMaduracionLineEdit.setFont(font)
        self.addMaduracionLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addMaduracionLineEdit.setText("")
        self.addMaduracionLineEdit.setMaxLength(7)
        self.addMaduracionLineEdit.setObjectName("addMaduracionLineEdit")
        self.addCostoLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addCostoLineEdit.setGeometry(QtCore.QRect(380, 410, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addCostoLineEdit.setFont(font)
        self.addCostoLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addCostoLineEdit.setText("")
        self.addCostoLineEdit.setMaxLength(9)
        self.addCostoLineEdit.setObjectName("addCostoLineEdit")
        self.addTamanoLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.addTamanoLineEdit.setGeometry(QtCore.QRect(380, 300, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.addTamanoLineEdit.setFont(font)
        self.addTamanoLineEdit.setStyleSheet("border: 3px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"padding-left: 5px;")
        self.addTamanoLineEdit.setText("")
        self.addTamanoLineEdit.setMaxLength(5)
        self.addTamanoLineEdit.setObjectName("addTamanoLineEdit")
        self.subtitleLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.subtitleLabel.setGeometry(QtCore.QRect(200, 20, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(True)
        self.subtitleLabel.setFont(font)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.errorLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.errorLabel.setGeometry(QtCore.QRect(20, 510, 881, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: rgb(255, 19, 19);")
        self.errorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.logoutOptionsGroupBox, 1, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 90)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setRowStretch(0, 10)
        self.gridLayout.setRowStretch(1, 90)

        self.retranslateUi(addVariedadWindow)
        self.closeDialogButton.clicked.connect(addVariedadWindow.closeDialog) # type: ignore
        self.cancelDialogButton.clicked.connect(addVariedadWindow.closeDialog) # type: ignore
        self.acceptDialogButton.clicked.connect(addVariedadWindow.doDialogAction) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addVariedadWindow)
        addVariedadWindow.setTabOrder(self.closeDialogButton, self.addVariedadLineEdit)
        addVariedadWindow.setTabOrder(self.addVariedadLineEdit, self.addMaduracionLineEdit)
        addVariedadWindow.setTabOrder(self.addMaduracionLineEdit, self.addTamanoLineEdit)
        addVariedadWindow.setTabOrder(self.addTamanoLineEdit, self.addCostoLineEdit)
        addVariedadWindow.setTabOrder(self.addCostoLineEdit, self.cancelDialogButton)
        addVariedadWindow.setTabOrder(self.cancelDialogButton, self.acceptDialogButton)

    def retranslateUi(self, addVariedadWindow):
        _translate = QtCore.QCoreApplication.translate
        addVariedadWindow.setWindowTitle(_translate("addVariedadWindow", "Form"))
        self.titleLabel.setText(_translate("addVariedadWindow", "Agregar Nueva Variedad"))
        self.closeDialogButton.setText(_translate("addVariedadWindow", "X"))
        self.acceptDialogButton.setText(_translate("addVariedadWindow", "Agregar"))
        self.cancelDialogButton.setText(_translate("addVariedadWindow", "Cancelar"))
        self.tamanoLabel.setText(_translate("addVariedadWindow", "Tamaño promedio:"))
        self.variedadNameLabel.setText(_translate("addVariedadWindow", "Nombre de la Variedad"))
        self.tiempoLabel.setText(_translate("addVariedadWindow", "Tiempo de maduración:"))
        self.costoLabel.setText(_translate("addVariedadWindow", "Costo por \n"
"Hectárea plantada:"))
        self.addVariedadLineEdit.setPlaceholderText(_translate("addVariedadWindow", "Ej. Blanca"))
        self.addMaduracionLineEdit.setPlaceholderText(_translate("addVariedadWindow", "Ej. 60-90"))
        self.addCostoLineEdit.setPlaceholderText(_translate("addVariedadWindow", "Ej. 25000"))
        self.addTamanoLineEdit.setPlaceholderText(_translate("addVariedadWindow", "Ej. 32.00"))
        self.subtitleLabel.setText(_translate("addVariedadWindow", "Ingrese los datos de la Variedad"))
        self.errorLabel.setText(_translate("addVariedadWindow", "Invalid Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addVariedadWindow = QtWidgets.QWidget()
    ui = Ui_addVariedadWindow()
    ui.setupUi(addVariedadWindow)
    addVariedadWindow.show()
    sys.exit(app.exec())
